# config file for sct_run_batch
path_data: /scratch/sabeda/???
path_output: /scratch/sabeda/ukbiobank_results
script: /home/sabeda/ukbiobank-spinalcord-csa/process_data.sh
script_args: $PATH_GRADCORR_FILE
jobs: -1
batch_log: sct_run_batch_log.txt
continue_on_error: 1
subject_prefix: sub-
zip: true