# config file for sct_run_batch for run_all.py script
path_data: /scratch/sabeda/uk-biobank
path_output: /scratch/sabeda/ukbiobank_results
script: /home/sabeda/ukbiobank-spinalcord-csa/process_data.sh
jobs: -1
batch_log: sct_run_batch_log.txt
continue_on_error: 1
subject_prefix: sub-